CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
HIS_TOKEN_INDEX = -300
WP_TOKEN_INDEX = -400
WAYPOINT_LABEL_TOKEN = -777
WAYPOINT_INPUT_TOKEN = 1
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_HISTORY_TOKEN = "<his>"
DEFAULT_WP_TOKEN = "<wp>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"
